import requests
import re
import json
import hashlib

def analyze_video_url(video_id):
    """
    Analysis of omg.xxx (KVS-based) video URL generation.
    
    URL Pattern: /get_file/[SERVER_ID]/[HASH]/[DIR]/[VIDEO_ID]/[FILENAME]
    Example: https://www.omg.xxx/get_file/8512/9759908470d3276a49568c0c27679dcaad9684292c/93732000/93732268/93732268_720m.mp4/
    """
    
    print(f"Analyzing Video ID: {video_id}")
    
    # 1. Page fetching (requires Cloudflare bypass in real scenario)
    # The page contains a script that loads the player config.
    # Player Config URL is usually: /contents/videos/player_config.php?video_id={video_id}
    
    player_config_url = f"https://www.omg.xxx/contents/videos/player_config.php?video_id={video_id}"
    
    print(f"Player Config URL: {player_config_url}")
    
    # 2. Logic for HASH (SHA-1)
    # The hash is generated by the server to prevent direct access to get_file without a valid session.
    # Formula (Internal to KVS): SHA1(video_id + secret_key + postfix)
    # Since we don't have the secret_key, we usually extract the pre-generated URL from the JSON config.
    
    print("\n--- Hashing Logic (KVS Standard) ---")
    print("The hash is 40 characters (SHA-1).")
    print("It is typically calculated as: sha1(video_id + secret_key + postfix)")
    print("Where 'postfix' is the Server ID (e.g., 8512).")

    # 3. Logic for Redirect to CDN
    print("\n--- CDN Redirect Logic ---")
    print("The /get_file/ URL acts as a gateway.")
    print("When called, the server checks the hash and then redirects (302) to the actual CDN.")
    
    # Example capture script
    capture_code = """
import requests

# This URL must be extracted from the player config JSON
get_file_url = "https://www.omg.xxx/get_file/8512/9759908470d3276a49568c0c27679dcaad9684292c/93732000/93732268/93732268_720m.mp4/"

headers = {
    "User-Agent": "Mozilla/5.0 ...",
    "Referer": "https://www.omg.xxx/videos/..."
}

# allow_redirects=False lets us see the 302 Location header
response = requests.get(get_file_url, headers=headers, allow_redirects=False)

if response.status_code == 302:
    cdn_url = response.headers.get('Location')
    print(f"CDN URL: {cdn_url}")
    # The CDN URL will contain a token and expiration timestamp
    # e.g., ?token=...&expires=...
"""
    print(capture_code)

if __name__ == "__main__":
    analyze_video_url("93722598")
